- name: Config
  ios_config:
    lines:
      # - spanning-tree mode rapid-pvst
      # - spanning-tree extend system-id
      # - spanning-tree pathcost method long
      # - spanning-tree portfast default
      - no spanning-tree vlan 1-4094 priority