---
- name: STP Check 
  hosts: all
  connection: network_cli
  gather_facts: true
  vars:
    ansible_network_os: ios
    ansible_command_timeout: 600
  
  tasks:
    # CHECK IF THE VERSION OF THE DEVICE IS BETWEEN 15 AND 16
    - name: Version 15-17
      #Execute the task list
      ansible.builtin.include_tasks: "{{ item }}"
      loop:  
        - 15_Check_trunk.yml    
        - 15_Config.yml      
      when: 
        - ansible_net_version is version('15','>=')
        - ansible_net_version is version('17','<')

            # CHECK IF THE VERSION OF THE DEVICE IS BETWEEN 15 AND 16
    
    - name: Version 17-18 
      #Execute the task list
      ansible.builtin.include_tasks: "{{ item }}"
      loop:  
        - 17_Check_trunk.yml    
        - 17_Config.yml      
      when: 
        - ansible_net_version is version('17','>=')
        - ansible_net_version is version('18','<')